### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by jounathaen** [hermitcore/hermit-entry#1]
As this is a crate with a public interface now, we should better document the interface.

**Comment by mkroening** [comment]
Yeah, that's the main goal of this project. Before, the API has to be analyzed, checked and reworked, though. I created a Roadmap: https://github.com/hermitcore/hermit-entry/issues/2

In the end you can expect 100% of this crate to be documented well. The current API is just a unified status quo. The only unsafe function of the current API is already documented thoroughly:

https://github.com/hermitcore/hermit-entry/blob/ae58010dac25af8ccd4be1b44646912c4ba0219d/src/kernel.rs#L49-L69

**Comment by mkroening** [comment]
I added docs for everything in 7bae22e6fdd48f7be723340a95af5d8e13c281a3.
