### ISSUE TITLE
Cmdline is invalid

### ISSUE THREAD

**Issue by stlankes** [hermitcore/hermit-entry#3]
I am not able to pass arguments to the programs. I would say that this crate ignores the commandline.

**Comment by mkroening** [comment]
I made a small mistake migrating the loader to this crate. A fix is pending: https://github.com/hermitcore/rusty-loader/pull/132

I checked the other fields and no others should be missing.

**Comment by mkroening** [comment]
Fixed in https://github.com/hermitcore/rusty-loader/pull/132.
